---
title: "HSS Summary Report"
author: "Renze Terpstra"
date: "3/11/2022"
output: 
  word_document:
  pdf_document:
params:
  location: Location
  month: Month
  year: 2022
  language: 
    label: "Select language"
    value: en
    input: select
    choices: [en, ar]
  grouping:
    label: "Grouping"
    value: district
    input: select
    choices: [district, gender] 
  tables:
    label: "Table type"
    value: percent
    input: select
    choices: [percent, count] 
  data: 
    label: "Input dataset"
    value: 
    input: file
  dictionary:
    label: "Input XLS form"
    value:
    input: file
  lookup:
    label: "Input lookup (.do) file"
    value:
    input: file

  # add R objects by including !r before the name
  # You could use output_file = paste0("Summary-", location, "-", month, "-", year, .docx) to automatically generate proper filenames
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(devtools)
library(knitr)
library(questionr)
library(flextable)
library(officer)
library(readxl)
load_all()
data <- testdata()
dict_var <- hssdict(params$dictionary, type = "vars")
dict_val <- hssdict(params$dictionary, type = "vals")
lookuplist <- hsslookup(params$lookup)
```

# `r params$location` - `r params$month` `r params$year`

## This is an example of a contingency table

```{r singleresponse, echo = FALSE}
t <- hssfreqtable(data, "singleresponse", params$grouping)
p <- hsschisq(data, "singleresponse", params$grouping)
t <- flextable(t)
t <- hsslabel(t, "Q0_1_a", dict_var, dict_val, lang = params$language)
t <- hssformat(t)
knit_print(t)
```



If we manually set the p-value to something else, the text will change accordingly
```{r pval, echo = TRUE}
p <- 0.001
paste("Chi-squared is ", if(p > 0.05) {"not"}, " significant (p = ", p, ")", sep = "")

```

## This is an example of a multi-response contingency table


```{r multi, echo=FALSE}
t <- hssmultitable(df = data, resp = c("multi_option1", "multi_option2", "multi_option3"), group = params$grouping)
# p <- hsschisq(data, c("multi_option1", "multi_option2", "multi_option3"), group = params$grouping)
t[1, "p"] <- 0.001
t <- flextable(t)
t <- hssformat_multi(t)
t
```



