---
title: "HSS Summary Report"
author: "Renze Terpstra"
date: "3/11/2022"
output:
  word_document:
  pdf_document:
params:
  location: Location
  month: Month
  year: 2022
  language:
    label: "Select language"
    value: english
    input: select
    choices: [english, arabic]
  grouping:
    label: "Grouping"
    value: gender
    input: select
    choices: [district, gender, county]
  tables:
    label: "Table type"
    value: percent
    input: select
    choices: [percent, count]
  data:
    label: "Input dataset"
    value:
    input: file
  dictionary:
    label: "Input XLS form"
    value:
    input: file
  lookup:
    label: "Input lookup (.do) file"
    value:
    input: file

  # add R objects by including !r before the name
  # You could use output_file = paste0("Summary-", location, "-", month, "-", year, .docx) to automatically generate proper filenames
  # use options(shiny.maxRequestSize=30*1024^2) to circumvent 5MB file size limit
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(devtools)
library(knitr)
library(questionr)
library(flextable)
library(officer)
library(readxl)
library(haven)
library(dplyr)
load_all()
data <- read_dta(params$data)
dict_var <- hssdict(params$dictionary, type = "vars")
dict_val <- hssdict(params$dictionary, type = "vals")
lookuplist <- hsslookup(params$lookup)
```

# HSS Summary
## `r params$location` - `r params$month` `r params$year`

## Demographics

```{r table_single, echo = FALSE, eval= FALSE}
t <- hsstable_single(data, question, params$grouping)
p <- hsschisq(data, question, params$grouping)
t <- flextable(t)
t <- hsslabel(t, question, dict_var, dict_val, lang = params$language, lookup = TRUE, lookuplist)
t <- hssformat(t)
```
<br><br>

```{r gender, echo = FALSE}
question <- "gender"
<<table_single>>
t
```
<br><br>
`r question <- "age_group"`
```{r age, echo = FALSE}
question <- "age_group"
<<table_single>>
t
print("test")
```
